services:
  vp_web:
    container_name: vp_web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./api:/usr/local/apache2/htdocs
    depends_on:
      - vp_php

  vp_php:
    container_name: vp_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    tty: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=vp_db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
    restart: always
    volumes:
      - ./api:/usr/local/apache2/htdocs
    depends_on:
      - vp_db

  vp_db:
    container_name: vp_db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  redis:
    image: "redis:latest"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis:/data"

